jobs:
  include:
   - dist: xenial
     arch: amd64
     language: android
     jdk: openjdk11
     script:
      #- ./script2
      - java -version
      - echo $JAVA_HOME
      - echo $PATH
   - dist: bionic
     arch: amd64
     language: android
     jdk: openjdk11
     script:
      #- ./script2
      - java -version
      - echo $JAVA_HOME
      - echo $PATH
   - dist: focal
     arch: amd64
     language: android
     jdk: openjdk11
     script:
      #- ./script2
      - java -version
      - echo $JAVA_HOME
      - echo $PATH
