language: android
jdk: oraclejdk11 # comment because there is a workaround on before_install

env:
  global:
    - BUILD_API=31
    - BUILD_TOOLS=31.0.0
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/cmdline-tools/latest

android:
  components:
    - tools

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

